import loadPopularMovies from "./js/load-popular-movies"
import getGenres from "./js/get-genres"
import getMoviesDetails from "./js/getMoviesDetails"
import "./js/loader"
import "./js/open-modal-window"
import "./js/modal-footer-window"