import loadPopularMovies from "./js/load-popular-movies"
import getGenres from "./js/get-genres"
import getMoviesDetails from "./js/getMoviesDetails"
import loadSelectedMovies from "./js/load-selected-movies"
import "./js/loader"